title : Don't Global Me Bro
tagline: Adventure in Web Dev
author :
  name : Vikki
  email : vikki.read@gmail.com
  github : dontglobalmebro
  twitter : vikkiread
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  

